# Generated by Django 4.2.4 on 2023-08-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'ordering': ['name'], 'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
    ]
