# Generated by Django 4.2.4 on 2023-08-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_blog_alter_contacts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=0, verbose_name='Номер версии продукта')),
                ('version_name', models.CharField(max_length=150, verbose_name='Имя версии продукта')),
                ('active_is', models.BooleanField(default=False, verbose_name='Признак активности продукта')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.flowers', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия букета',
                'verbose_name_plural': 'Версии букетов',
            },
        ),
    ]
