# Generated by Django 4.2.4 on 2023-08-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
