# Generated by Django 4.2.4 on 2023-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_flowers_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_publication',
        ),
        migrations.AddField(
            model_name='flowers',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Признак публикации '),
        ),
    ]
