# Generated by Django 4.2.4 on 2023-09-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_blog_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'ordering': ['name'], 'permissions': [('set_published_status', 'Can publish post')], 'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
    ]
